pipeline {
    agent {
        docker{
            image 'python:2.7.16-slim'
        }
    }


    stages {
        stage('Build') {
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Compiling vote app'
                dir('vote'){
                    sh 'pip install -user -r requirements.txt'
                }
            }
        }
        stage('Test') {
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Running unit tests on vote app'
                dir('vote'){
                    sh 'nosetests -v'
                }
            }
        }
    }

    post {
        always {
            echo 'Build pipeline for vote app is complete'
        }
        failure {
            slackSend (channel: "instavote-cd", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success {
            slackSend (channel: "instavote-cd", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}
