pipeline {
   agent any

   tools {
      maven 'Maven 3.6.3'
   }

   stages {
      stage('Build') {
         steps {
            echo 'Compiling worker app'
            dir('worker'){
                sh 'mvn compile' 
            }
         }
      }
      stage('Test') {
         steps {
            echo 'Running unit tests on worker app'
            dir('worker'){
                sh 'mvn clean test' 
            }
         }
      }
      stage('Package') {
         steps {
            echo 'Packaging worker app'
            dir('worker'){
                sh 'mvn package' 
            }
         }
      }
    }
    
    post {
        always {
            echo 'Build pipeline for worker is complete'
        }
    }
}

